### ISSUE TITLE
Unable to find a specification for `Tabby`

### ISSUE THREAD

**Issue by freddy5566** [hyperoslo/Tabby#29]
hi 

it seems like that this library cannot be found via CocoaPods

i add `pod 'Tabby'` inside my podfile, but i cannot find this awesome pod

**Comment by tim-kozak** [comment]
pod 'Tabby', git: 'https://github.com/hyperoslo/Tabby'

**Comment by tim-kozak** [comment]
but it's not working because of swift 4.2

**Comment by freddy5566** [comment]
Hi @comonitos, 

thanks for your response

but I've fixed it by just use another lib

best,
Jamfly

**Comment by fukemy** [comment]
Hi, whats name of another lib you used?

**Comment by freddy5566** [comment]
@fukemy, sorry it has been years, I've already switch my focus from iOS development to NLP. Unfortunately, I forget the actual pod name. Sorry I could not help.
