### ISSUE TITLE
Ability to refresh color settings

### ISSUE THREAD

**Issue by zenangst** [hyperoslo/Tabby#8]
It would be nice and nifty to be able to invoke a `reconfigure` method to refresh the colors that are used in Tabby. Lets say that you application gets information from a backend about which colors to use in the Tabby, then if the color changes on the backend, you could apply this colors to the `TabbyController` without having to reinitialize a new `TabbyController` or recreate the items that are in the tab bar.

**Comment by RamonGilabert** [comment]
This should be happening already. Every time you tap into a cell, it should call the color constant, so by changing the color constant it should work when you tap. Isn't that good enough?

**Comment by RamonGilabert** [comment]
The color of the indicator did not change, I'm doing that now.
