### ISSUE TITLE
Feature intercepting tab bar selections

### ISSUE THREAD

**Issue by zenangst** [hyperoslo/Tabby#9]
I think it could be useful to be able to intercept a navigation before it happens. Play with the idea that you have an item in your tab bar that actually leaves the application, then you don't want that to switch out the controller and to show and empty one when you get back into your application.

We can use Facebook and Facebook Messenger as an example, if you tap that item, you don't navigate inside Facebook, you are transported to Messenger. When you come back to Facebook, it is exactly like you left it.

I don't think this would be to hard to achieve if we change the delegate method on `TabbyController` to return a boolean value. If it is set to `true`, it would change, if `false`, then it is up to the developer to decide what is suppose to happen when a user taps the item.

So instead of this;
https://github.com/hyperoslo/Tabby/blob/master/Sources/TabbyController.swift#L8

``` swift
func tabbyDidPress(item: TabbyBarItem)
```

You would have something like this;

``` swift
func tabbyDidPress(item: TabbyBarItem) -> Bool
```

**Comment by zenangst** [comment]
Or you could add a property on the item that you add to tabby to indicate what type of item it is.

``` swift
enum TabBarItemType {
   case .Internal, .External
}
```

**Comment by onmyway133** [comment]
The `TabBarItemType` approach sounds nifty, but the `delegate` approach seems to be more flexible I think

**Comment by RamonGilabert** [comment]
Gonna go for the delegate method. Simpler for the public API.

**Comment by RamonGilabert** [comment]
All right, so I added a `Behavior` that will reside in every `TabBarItem`. Such behavior has two possibilities: `systematic` that is the one that Tabby offers, or `custom`, which is your one. It defaults to `systematic`, if you set to `custom`, nothing will happen.

**Comment by zenangst** [comment]
🚀 🚀 🚀 🚀
